fullnameOverride: ${release_name}
region: ${region}
settings:
  clusterName: ${cluster_name}
  clusterEndpoint: ${cluster_endpoint}
  interruptionQueue: ${karpenter_queue_name}
  featureGates:
    spotToSpotConsolidation: true
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: ${irsa_role}

